[project]
name = "snipe"
version = "0.1.0"
description = "lightweight, fast, accurate estimator for basic sequence alignment metrics and more."
authors = ["Mohamed Abuelanin <mabuelanin@gmail.com>", "Tamer A. Mansour <drtamermansour@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]
readme = "README.md"
homepage = "https://snipe-bio.github.io/snipe/"
repository = "https://github.com/snipe-bio/snipe"

[tasks]
fmt = "ruff format"
lint = "ruff check --fix"
snipe = "python -m snipe.cli"


[dependencies]
python = ">=3.12"
sourmash = ">=4.8.7"
tqdm = ">=4.66.2"
numpy = ">=1.26.4"
pandas = ">=2.2.1"
jax = ">=0.4.25,<0.5"
click = ">=8.1.7"
jaxlib = ">=0.4.23,<0.5"
pytest = ">=8.1.1,<8.2"
nodejs = ">=20.9.0,<20.10"
ijson = ">=3.2.3,<3.3"
